name: flutter_app_sp2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.16.0+1 #1.0.0
  
  #flutter_localizations:
    #sdk: flutter
  flutter:
    sdk: flutter

  firebase_auth: ^0.20.1 #1.0.1
  sms_autofill: ^1.3.1
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^1.2.0 #2.0.1
  firebase_messaging: ^6.0.16
  overlay_support: ^1.0.4 #1.2.0
  firebase_core: ^0.7.0 #1.0.0
  animated_text_kit: ^1.3.0
  modal_progress_hud: ^0.1.3
  location: ^3.0.0
  geolocator: ^6.2.1
  #intl: ^0.17.0
  adaptive_theme: ^1.1.0
  get: ^3.13.2
  geoflutterfire:
    git: git://github.com/DarshanGowda0/GeoFlutterFire.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
